// actionTypes.js

// Monthly Revenue
export const GET_REVENUE_MONTHLY_REQUEST = 'GET_REVENUE_MONTHLY_REQUEST';
export const GET_REVENUE_MONTHLY_SUCCESS = 'GET_REVENUE_MONTHLY_SUCCESS';
export const GET_REVENUE_MONTHLY_FAILURE = 'GET_REVENUE_MONTHLY_FAILURE';

// Category-wise Revenue
export const GET_REVENUE_CATEGORY_REQUEST = 'GET_REVENUE_CATEGORY_REQUEST';
export const GET_REVENUE_CATEGORY_SUCCESS = 'GET_REVENUE_CATEGORY_SUCCESS';
export const GET_REVENUE_CATEGORY_FAILURE = 'GET_REVENUE_CATEGORY_FAILURE';
